### ISSUE TITLE
Belgian coordinates shown as Morocco

### ISSUE THREAD

**Issue by KempDewulf** [coordinates2country/sample#1]
When coordinates in Belgium are given, 50.860, 4.325 for instance, it returns Morocco as the country.

**Comment by Berthje** [comment]
Correct @KempDewulf, I got this aswell

**Comment by nicolas-raoul** [comment]
Thanks for your feedback, I will fix this as soon as possible!

**Comment by nicolas-raoul** [comment]
This is fixed now with version 1.3.
Please do not hesitate to report other issues. :-)

**Comment by nicolas-raoul** [comment]
Sorry I meant 1.4 :-)

**Comment by Berthje** [comment]
I changed the version in implementation from 1.2 to 1.4 and rebuilded my
project as it should.
Now I get this error:

 Could not resolve io.github.coordinates2country:coordinates2country:1.4.
No matching variant of
io.github.coordinates2country:coordinates2country:1.4 was found. The
consumer was configured to find a library for use during compile-time,
compatible with Java 17, preferably in the form of class files, preferably
optimized for standard JVMs, and its dependencies declared externally but:
          - Variant 'apiElements' capability
io.github.coordinates2country:coordinates2country:1.4 declares a library
for use during compile-time, packaged as a jar, and its dependencies
declared externally:
              - Incompatible because this component declares a component,
compatible with Java 21 and the consumer needed a component, compatible
with Java 17
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment
(preferred optimized for standard JVMs)
          - Variant 'javadocElements' capability
io.github.coordinates2country:coordinates2country:1.4 declares a component
for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation
and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment
(preferred optimized for standard JVMs)
                  - Doesn't say anything about its target Java version
(required compatibility with Java 17)
                  - Doesn't say anything about its elements (required them
preferably in the form of class files)
          - Variant 'runtimeElements' capability
io.github.coordinates2country:coordinates2country:1.4 declares a library
for use during runtime, packaged as a jar, and its dependencies declared
externally:
              - Incompatible because this component declares a component,
compatible with Java 21 and the consumer needed a component, compatible
with Java 17
              - Other compatible attribute:
                  - Doesn't say anything about its target Java environment
(preferred optimized for standard JVMs)
          - Variant 'sourcesElements' capability
io.github.coordinates2country:coordinates2country:1.4 declares a component
for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation
and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java environment
(preferred optimized for standard JVMs)
                  - Doesn't say anything about its target Java version
(required compatibility with Java 17)
                  - Doesn't say anything about its elements (required them
preferably in the form of class files)

[image: image.png]

is it possible you forgot something or am i doing it wrong, I just changed
the version in build.gradle and the import doesn't work anymore.

Thanks!

**Comment by Berthje** [comment]
made an issue for that in case it is a bug so you can attach it to that
issue:

https://github.com/coordinates2country/coordinates2country/issues/4
